brace_style = "PreferSameLine"
comment_width = 79
control_brace_style = "ClosingNextLine"
format_code_in_doc_comments = true
format_strings = true
fn_args_layout = "Compressed"
group_imports = "StdExternalCrate"
hex_literal_case = "Lower"
imports_granularity = "Item"
match_block_trailing_comma = true
max_width = 79
newline_style = "Unix"
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
tab_spaces = 2
trailing_comma = "Vertical"
trailing_semicolon = true
use_small_heuristics = "Max"
version = "Two"
wrap_comments = true
